version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - 80:5000
      - 443:5000
    networks:
      - web-flask
    volumes:
      #- .:/usr/src/http_check/
      - ./databases:/usr/src/databases/

networks:
  web-flask: